display:
  mode: 0
assets:
  background: [assets, images,"background.jpg"]
  font: [assets, fonts, "Montserrat-SemiBold.ttf"]
colors:
  text: [255,255,255]
  button: [255,255,255,50]
  button_hover: [255,255,255,100]
  maze_container: [255,255,255,70]
  menu_container: [255,255,255,70]
  info_bars: [0, 0, 127, 127]
  maze_path: [0, 0, 127, 127]
ui_propotions:
  buttons_padding: 0.005
  side_menu:
    width: 0.2
    pos_x: 0.01
    pos_y: 0.1
  control_menu:
    width: 0.2
    pos_x: 0.22
    pos_y: 0.1
  solve_menu:
    width: 0.2
    pos_x: 0.01
    pos_y: 0.28
  solve_control_menu:
    width: 0.2
    pos_x: 0.22
    pos_y: 0.28 
  settings_menu:
    width: 0.2
    pos_x: 0.01
    pos_y: 0.47
  selection_button: 
    width: 0.2
    height: 0.05
    pos_x: 0
    pos_y: 0.05
    text_offset: 0.1
  bars: 
    text_offset: 0.1
    topbar:
      pos_x: 0
      pos_y: 0
      width: 1
      height: 0.05
    bottombar:
      pos_x: 0
      pos_y: 0.95
      width: 1
      height: 0.05
  maze_container: 
    width: 0.8
    height: 0.8
    pos_x: 0.01
    pos_y: 0.1
  border_radius: 10
  font: 0.035
text:
  app_name: "PathFinding 2.0"
  author: "Patryk Pyrkosz 119254"
  state: 
    status: "Status"
    waiting: "Waiting for action"
    solving: "Solving maze"
    generating: "Generating maze"
    generated: "Maze generated successfuly"
    solved: "Maze solved successfuly"
constants:
  wall: 0
  path: 1
  s_path: 2
  starting_v: 3
  ending_v: 4
