display:
  mode: 0
assets:
  background: [assets, images,"background.jpg"]
  font: [assets, fonts, "Montserrat-SemiBold.ttf"]
colors:
  text: [255,255,255]
  button: [255,255,255,50]
  button_hover: [255,255,255,100]
  maze_container: [255,255,255,70]
  info_bars: [0, 0, 127, 127]
ui_propotions:
  selection_button: 
    width: 0.2
    height: 0.05
  bars: 
    width: 1
    height: 0.05
    text_offset: 0.1
    topbar:
      pos_x: 0
      pos_y: 0
    bottombar:
      pos_x: 0
      pos_y: 0.95
  maze_container: 
    width: 0.8
    height: 0.8
  border_radius: 10
  font: 0.035
text:
  app_name: "PathFinding 2.0"
  author: "Patryk Pyrkosz 119254"
  status: 
    status: "Status"
    working: "Working"
    done: "Done"
    solving: "Solving maze"
    generating: "Generating maze"
  
